# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

command:
  check-scdf-composed-task-runner-version:
    timeout: 20000
    exec: timeout --preserve-status 15 java -jar /opt/bitnami/spring-cloud-dataflow-composed-task-runner/scdf-composed-task-runner.jar
    exit-status: 1
    stdout:
      - "{{ .Env.APP_VERSION }}"
file:
  /opt/bitnami/spring-cloud-dataflow-composed-task-runner/scdf-composed-task-runner.jar:
    exists: true
    filetype: symlink
    linked-to: "spring-cloud-dataflow-composed-task-runner-{{ .Env.APP_VERSION }}.jar"
