# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

command:
  check-grafana-plugins:
    exit-status: 0
    exec: grafana cli --pluginsDir /opt/bitnami/grafana/default-plugins/ plugins ls
    stdout:
    {{ range $plugin := .Vars.plugins }}
      - "{{ $plugin }}"
    {{ end }}
user:
  grafana:
    exists: true
group:
  grafana:
    exists: true
