# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

file:
  /opt/bitnami/common/lib/libmaxminddb.so:
    exists: true
  /var/log/nginx/access.log:
    exists: true
    filetype: symlink
    linked-to: /dev/stdout
  /var/log/nginx/error.log:
    exists: true
    filetype: symlink
    linked-to: /dev/stderr
command:
  test-nginx-config:
    exec: nginx -t
    exit-status: 0
  test-capabilities:
    exec: getcap /nginx-ingress-controller /usr/local/nginx/sbin/nginx
    exit-status: 0
    stdout:
      - /nginx-ingress-controller .*cap_net_bind_service[+=]ep/
      - /.*nginx .*cap_net_bind_service[+=]ep/
