# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

command:
  # The cli jar doesn't really have a help flag
  # and exits with a "status=1" when not properly started.
  check-keycloak-config-cli:
    exec: java -jar /opt/bitnami/keycloak-config-cli/keycloak-config-cli.jar
    exit-status: 1
    timeout: 10000
    stdout:
      - "Started KeycloakConfigApplication"
  # Besides the default one, we are packaging
  # one cli per keycloak major as done by upstream
  check-per-major-clis:
    exec: if [ $(ls /opt/bitnami/keycloak-config-cli/keycloak-config-cli-*.jar | wc -l) -eq 0 ]; then exit 1; fi
    exit-status: 0
