# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

command:
  # The original jar has the asset version in its filename
  check-app-version:
    exec: ls /opt/bitnami/prometheus-rsocket-proxy/prometheus-rsocket-proxy-*.jar
    exit-status: 0
    stdout:
    - "{{ .Env.APP_VERSION }}"
  check-proxy-jar:
    exec: timeout --preserve-status 10 java -jar /opt/bitnami/prometheus-rsocket-proxy/prometheus-rsocket-proxy.jar
    exit-status: 143
    timeout: 20000
    stdout:
      - "Started PrometheusRSocketProxy"
file:
  /opt/bitnami/prometheus-rsocket-proxy/prometheus-rsocket-proxy.jar:
    exists: true
    filetype: symlink
